package neu.edu.entity;
// Generated Apr 27, 2017 6:00:41 PM by Hibernate Tools 5.2.1.Final

/**
 * Cart generated by hbm2java
 */
public class Cart implements java.io.Serializable {

	private CartId id;

	public Cart() {
	}

	public Cart(CartId id) {
		this.id = id;
	}

	public CartId getId() {
		return this.id;
	}

	public void setId(CartId id) {
		this.id = id;
	}

}
