package neu.edu.entity;
// Generated Apr 27, 2017 11:34:47 PM by Hibernate Tools 5.2.1.Final

/**
 * PaymentInfo generated by hbm2java
 */
public class PaymentInfo implements java.io.Serializable {

	private PaymentInfoId id;
	private Integer cardYear;
	private Integer cardMonth;
	private Integer cardCvv;

	public PaymentInfo() {
	}

	public PaymentInfo(PaymentInfoId id) {
		this.id = id;
	}

	public PaymentInfo(PaymentInfoId id, Integer cardYear, Integer cardMonth, Integer cardCvv) {
		this.id = id;
		this.cardYear = cardYear;
		this.cardMonth = cardMonth;
		this.cardCvv = cardCvv;
	}

	public PaymentInfoId getId() {
		return this.id;
	}

	public void setId(PaymentInfoId id) {
		this.id = id;
	}

	public Integer getCardYear() {
		return this.cardYear;
	}

	public void setCardYear(Integer cardYear) {
		this.cardYear = cardYear;
	}

	public Integer getCardMonth() {
		return this.cardMonth;
	}

	public void setCardMonth(Integer cardMonth) {
		this.cardMonth = cardMonth;
	}

	public Integer getCardCvv() {
		return this.cardCvv;
	}

	public void setCardCvv(Integer cardCvv) {
		this.cardCvv = cardCvv;
	}

}
