package neu.edu.entity;
// Generated Apr 27, 2017 11:34:47 PM by Hibernate Tools 5.2.1.Final

/**
 * PaymentInfoId generated by hbm2java
 */
public class PaymentInfoId implements java.io.Serializable {

	private int userId;
	private int cardNumber;

	public PaymentInfoId() {
	}

	public PaymentInfoId(int userId, int cardNumber) {
		this.userId = userId;
		this.cardNumber = cardNumber;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getCardNumber() {
		return this.cardNumber;
	}

	public void setCardNumber(int cardNumber) {
		this.cardNumber = cardNumber;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PaymentInfoId))
			return false;
		PaymentInfoId castOther = (PaymentInfoId) other;

		return (this.getUserId() == castOther.getUserId()) && (this.getCardNumber() == castOther.getCardNumber());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getCardNumber();
		return result;
	}

}
