package neu.edu.entity;
// Generated Apr 27, 2017 11:34:47 PM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * UserProject generated by hbm2java
 */
public class UserProject implements java.io.Serializable {

	private Integer projectId;
	private UserAccount userAccount;
	private String projectName;
	private Integer categoryId;
	private String projectDesc;
	private String endDate;
	private String projectLocation;
	private Float projectPrice;
	private String projectPicture;
	private String startDate;
	private String projectStatus;
	private Set<UserProjectServices> userProjectServiceses = new HashSet<UserProjectServices>(0);

	public UserProject() {
	}

	public UserProject(UserAccount userAccount, String projectName, Integer categoryId, String projectDesc,
			String endDate, String projectLocation, Float projectPrice, String projectPicture, String startDate,
			String projectStatus, Set<UserProjectServices> userProjectServiceses) {
		this.userAccount = userAccount;
		this.projectName = projectName;
		this.categoryId = categoryId;
		this.projectDesc = projectDesc;
		this.endDate = endDate;
		this.projectLocation = projectLocation;
		this.projectPrice = projectPrice;
		this.projectPicture = projectPicture;
		this.startDate = startDate;
		this.projectStatus = projectStatus;
		this.userProjectServiceses = userProjectServiceses;
	}

	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	public UserAccount getUserAccount() {
		return this.userAccount;
	}

	public void setUserAccount(UserAccount userAccount) {
		this.userAccount = userAccount;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	public String getProjectDesc() {
		return this.projectDesc;
	}

	public void setProjectDesc(String projectDesc) {
		this.projectDesc = projectDesc;
	}

	public String getEndDate() {
		return this.endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	public String getProjectLocation() {
		return this.projectLocation;
	}

	public void setProjectLocation(String projectLocation) {
		this.projectLocation = projectLocation;
	}

	public Float getProjectPrice() {
		return this.projectPrice;
	}

	public void setProjectPrice(Float projectPrice) {
		this.projectPrice = projectPrice;
	}

	public String getProjectPicture() {
		return this.projectPicture;
	}

	public void setProjectPicture(String projectPicture) {
		this.projectPicture = projectPicture;
	}

	public String getStartDate() {
		return this.startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	public String getProjectStatus() {
		return this.projectStatus;
	}

	public void setProjectStatus(String projectStatus) {
		this.projectStatus = projectStatus;
	}

	public Set<UserProjectServices> getUserProjectServiceses() {
		return this.userProjectServiceses;
	}

	public void setUserProjectServiceses(Set<UserProjectServices> userProjectServiceses) {
		this.userProjectServiceses = userProjectServiceses;
	}

}
