package neu.edu.entity;
// Generated Apr 27, 2017 11:34:47 PM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * UserAccount generated by hbm2java
 */
public class UserAccount implements java.io.Serializable {

	private Integer id;
	private String userName;
	private String name;
	private Integer password;
	private String role;
	private Set<UserProject> userProjects = new HashSet<UserProject>(0);

	public UserAccount() {
	}

	public UserAccount(String userName, String name, Integer password, String role, Set<UserProject> userProjects) {
		this.userName = userName;
		this.name = name;
		this.password = password;
		this.role = role;
		this.userProjects = userProjects;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getPassword() {
		return this.password;
	}

	public void setPassword(Integer password) {
		this.password = password;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public Set<UserProject> getUserProjects() {
		return this.userProjects;
	}

	public void setUserProjects(Set<UserProject> userProjects) {
		this.userProjects = userProjects;
	}

}
