package neu.edu.bean;
// Generated Apr 27, 2017 11:55:16 AM by Hibernate Tools 5.2.1.Final

/**
 * Cart generated by hbm2java
 */
public class CartBean implements java.io.Serializable {

	private int userId;
	private Integer thisServiceId;

	public CartBean() {
	}

	public CartBean(int userId) {
		this.userId = userId;
	}

	public CartBean(int userId, Integer thisServiceId) {
		this.userId = userId;
		this.thisServiceId = thisServiceId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public Integer getThisServiceId() {
		return thisServiceId;
	}

	public void setThisServiceId(Integer thisServiceId) {
		this.thisServiceId = thisServiceId;
	}


}
